services:
  - docker

before_install:
  - docker pull spacevim/vims
  - docker inspect --format="{{.Id}}" spacevim/vims

jobs:
  include:
    - env: VIM=vim73
    - env: VIM=vim74
    - env: VIM=vim
    - env: VIM=neovim-stable
    - env: VIM=neovim


script:
  - docker run -it --rm spacevim/vims $VIM --version
