services:
  - docker

before_install:
  - docker pull spacevim/vims

script:
  - docker run -it --rm spacevim/vims vim73 --version
  - docker run -it --rm spacevim/vims vim74 --version
  - docker run -it --rm spacevim/vims vim --version
  - docker run -it --rm spacevim/vims neovim-stable --version
  - docker run -it --rm spacevim/vims neovim --version
